apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: first-pod
  ports:
    - port: 80
      #targetPort: 80 # vai assumir que os dois sao iguais a partir do primeiro
      nodePort: 30000
